### ISSUE TITLE
Uncaught Error: Cannot find module 'season'

### ISSUE THREAD

**Issue by CoffeyBlog** [lee-dohm/package-sync#29]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.20.1 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [package-sync](https://github.com/lee-dohm/package-sync) package 1.1.0

### Stack Trace

Uncaught Error: Cannot find module 'season'

```
At module.js:472

Error: Cannot find module 'season'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (Applications/Atom.app/Contents/Resources/app/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/package-sync-master/lib/package-list.coffee:1:8)
    at /packages/package-sync-master/lib/package-list.coffee:1:1)
    at /packages/package-sync-master/lib/package-list.coffee:1:1)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (Applications/Atom.app/Contents/Resources/app/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/package-sync-master/lib/package-sync.coffee:5:15)
    at /packages/package-sync-master/lib/package-sync.coffee:1:1)
    at /packages/package-sync-master/lib/package-sync.coffee:1:1)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (Applications/Atom.app/Contents/Resources/app/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at loadModule (/packages/package-sync-master/lib/index.coffee:6:18)
    at /packages/package-sync-master/lib/index.coffee:20:7)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:1338:34)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app/src/application-delegate.js:335:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -0:42.8.0 package-sync:sync (input.hidden-input)
```

### Non-Core Packages

```
atom-material-ui 2.0.4 
autoclose-html 0.23.0 
es6-javascript 1.0.0 
javascript-snippets 1.2.1 
language-javascript-jsx 0.3.7 
meteor-api 2.20.0 
meteor-snippets 0.5.0 
package-sync 1.1.0 
turbo-javascript 1.4.0 
```

**Comment by lee-dohm** [comment]
It looks like you're running package-sync in development mode and forgot to run `apm install` in the package directory to install the package's dependencies. You have a couple options:

1. Install the package normally using `apm install package-sync`
1. Run `apm install` in the directory where you've cloned package-sync to. It looks like that would be `/packages/package-sync-master`.
